'use client'

import { useCallback } from 'react'
import { useResources } from '@/shared/resources'

// Keys checked in GeneralResources.resx; the value is the English fallback when a key is missing or still loading.
export const USERS_TEXT = {
  Users: 'Users',
  User: 'User',
  AccessProfile: 'Access Profile',
  ContactGroup: 'Contact Group',
  Activity: 'Activity Log',
  DeveloperKey: 'Developer Key',
  Add: 'Add',
  Delete: 'Delete',
  Search: 'Search',
  UserName: 'User Name',
  AccessProfiles: 'Access Profile(s)',
  Email: 'E-mail',
  RealName: 'Full Name',
  Loading: 'Loading',
  Refresh: 'Refresh',
  AlertGeneralErrorDefault: 'There was an error while processing your request.',
  DeleteConfirmationMsg: 'Are you sure you want to delete selected items?',
  Confirm: 'Confirm',
  Cancel: 'Cancel',
  AlertDeleteSuccessDefault: 'The item was deleted succesfully.',
  AlertDeleteErrorDefault: 'There was an error while trying to delete the item.',
  Selected: 'Selected',
  Clear: 'Clear',
  Collapse: 'Collapse',
  NumberOfItemsPerPage: 'Number of items per page',
  Of: 'of',
  Next: 'Next',
  Previous: 'Previous',
  Total: 'Total',
  FieldsWithInputValidations: 'There are fields with input validation errors.',
  SelectAll: 'Select All',
  Save: 'Save',
  Required: 'Required',
  AccountActive: 'Account Active',
  Password: 'Password',
  ConfirmPassword: 'Confirm Password',
  AssociatedStudent: 'Associated Student',
  SearchStudent: 'Search student',
  EmailAddress: 'Email Address',
  FullName: 'Full Name',
  IsMobileAppLoggingActive: 'Mobile App Logging Active',
  Personas: 'Persons',
  SecurityLevelPermissions: 'Security Level Permissions',
  UpOrder: 'Up Order',
  DownOrder: 'Down Order',
  Select: 'Select',
  IsSuperUser: 'Is Super User',
  LecturerVisibility: 'Lecturer Visibility',
  Schools: 'Schools',
  Courses: 'Courses',
  Modules: 'Modules',
  Programmes: 'Programmes',
  Faculties: 'Colleges',
  Students: 'Students',
  None: 'None',
  Yes: 'Yes',
  No: 'No',
  TheConfirmationDoesNotMatchThePassword: 'The confirmation does not match the password',
  YouCantSaveUserWithAccessProfilesDuplicates: 'You cannot save a user with access profiles duplicates',
  TheUserYouAreTryingToCreateMustHaveAtLeastOneAccessProfileAssociatedWithIt:
    'The user you are trying to create must have at least one access profile associated with it.',
  AlertSaveSucceededDefault: 'The item was saved successfully.',
  AlertSaveErrorDefault: 'There was an error while trying to save the item.',
  Name: 'Name',
  GroupEmailAddress: 'Group Email Address',
  SendEmailsTo: 'Send Emails To',
  Function: 'Function',
  AssociatedTo: 'Associated To',
  ExpiryDate: 'Expiry Date',
  SetPassword: 'Set Password',
  PasswordWasSavedSuccesfuly: 'Password was saved succesfuly',
  Apply: 'Apply',
  Description: 'Description',
  AddUsers: 'Add Users',
  SearchUsers: 'Search users',
  EditFunction: 'Edit Function',
  CreateNewFunction: 'Create New Function',
  ContactGroupFunctionInfo: 'The function this contact group performs.',
  PleaseEnterAValidEmail: 'Please enter a valid email address.',
  ContactGroupYouAreTryingToCreateMustHaveAtLeastOneUserAssociatedGroupEmailWithIt:
    'The contact group you are trying to create must have at least one user or a group email address associated with it.',
  Course: 'Course',
  Faculty: 'College',
  Module: 'Module',
  Programme: 'Programme',
  School: 'School',
  Edit: 'Edit',
  EntityType: 'Type',
  ExternalKey: 'External Key',
  Restricted: 'Restricted',
  RestrictedAccessProfilesLegend: 'Restricted access profiles can only be assigned by users who hold them.',
  DefaultLandingPage: 'Default Landing Page',
  SiteAccess: 'Site Access',
  EventVisibility: 'Event Visibility',
  CaseVisibility: 'Case Visibility',
  WorkflowVisibility: 'Workflow Visibility',
  CopyProfile: 'Copy profile',
  NotSet: 'Not Set',
  HomeMenu: 'Home Menu',
  Lectures: 'Lectures',
  Reports: 'Reports',
  CfcAttendanceTitle: 'CFC Attendance',
  MyProfile: 'My Profile',
  Event: 'Event',
  Details: 'Details',
  Comment: 'Comment',
  Events: 'Events',
  CaseHistory: 'Case History',
  Access: 'Access',
  Site: 'Site',
  All: 'All',
  Admin: 'Admin',
  Web: 'Web',
  Type: 'Type',
  Logon: 'Logon',
  Page: 'Page',
  Action: 'Action',
  SelectRange: 'Select Range',
  DateRange: 'Date Range',
  From: 'From',
  To: 'To',
  Today: 'Today',
  Item: 'Item',
  Detail: 'Detail',
  Date: 'Date',
  Export: 'Export',
  StartDate: 'Start Date',
  EndDate: 'End Date',
  ExportAs: 'Export As',
  Pdf: 'Pdf',
  Csv: 'Csv',
  AdminSite: 'Administration Site',
  WebSite: 'WebSite',
  DefaultPage: 'Default Page',
  SeatsPageview: 'SEAtS Pageview',
  SeatsAction: 'SEAtS Action',
  SeatsCancel: 'SEAtS Cancel',
  SeatsLogon: 'SEAts Logon',
  ReportProcessing:
    'The report is being generated and a link to the report will appear on your notification screen',
  Actions: 'Actions',
  Close: 'Close',
} as const

// Not in GeneralResources; legacy hard-codes these (swgrid.js:816) or has no equivalent.
export const USERS_FALLBACK_ONLY = {
  page: 'Page',
  noItems: 'There are no items to show.',
  expand: 'Expand',
  first: 'First',
  last: 'Last',
  clearSearch: 'Clear search',
  noAccess: 'You do not have permission to view users.',
  select: 'Select',
  // swapp.js:2646 hard-codes this message.
  specialCharacters: 'Special characters are not allowed .',
  studentNotSelected: 'There is no item selected.',
  notFound: 'This user could not be found.',
  noneOption: '[None]',
  safeMode: 'Saving is turned off in this environment (safe mode).',
  newUser: 'New user',
  noPageAccess: 'You do not have permission to view this page within the SEAtS application.',
  // AccessProfile/Index.cshtml:76 hard-codes this message.
  profileRestricted: 'You do not have permission to access this profile.',
  // userDetailsController.js:156, 168 and Details.cshtml:36 hard-code these.
  sendResetLink: 'Send Password Reset Link',
  selectedOf: (n: number, total: number) => `${n} of ${total} selected`,
  selectAll: 'Select all',
  clearAll: 'Clear',
  noMatches: 'Nothing matches that search.',
  noEventTypes: 'This tenant has no event types yet.',
  noCaseTypes: 'This tenant has no case types yet.',
  noWorkflows: 'This tenant has no workflows yet.',
  eventVisibilityHint:
    'Which timeline event types show on a student, and whether details and comments come with them.',
  caseVisibilityHint: 'Which case types this profile may open.',
  workflowVisibilityHint: 'Which workflows this profile may act in.',
  setPasswordHint: 'Choose a password yourself and hand it over.',
  sendResetLinkHint: 'Email the user a link so they choose their own.',
  resetLinkSent: 'Password reset link sent successfully.',
  resetLinkFailed: 'Failed to send password reset link.',
  newContactGroup: 'New contact group',
  contactGroupNotFound: 'This contact group could not be found.',
  newAccessProfile: 'New access profile',
  // accessProfileDetailsController.js:145 hard-codes this message.
  landingPageNotAllowed: "Access profile lacks the 'Access' permission for the selected default landing page",
  // seats-admin-audit.html:188, 247 and 252 hard-code these.
  clean: 'Clean',
  activityFilters: 'Filters',
  yesterday: 'Yesterday',
  last7Days: 'Last 7 Days',
  last14Days: 'Last 14 Days',
  last30Days: 'Last 30 Days',
  views: 'Views',
  activeFilters: 'Active filters',
  remove: 'Remove',
  chooseMonthYear: 'Choose month and year',
  userNameColumn: 'User Name',
  userFullNameColumn: 'User Full Name',
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
  exportBlocked: 'Exporting is turned off in this environment (safe mode).',
  searchPermissions: 'Search permissions',
  levelNone: 'None',
  levelView: 'View',
  levelEdit: 'Edit',
  levelFull: 'Full',
  levelCustom: 'Custom',
  noPermissions: 'No access',
  chooseActions: 'Choose actions',
  noPermissionMatches: 'No permissions match your search.',
  livePreview: 'Live preview',
  livePreviewHint: 'See exactly what users with this profile get. Every click shows up here.',
  livePreviewEmpty: 'This profile cannot open any page yet.',
  previewPages: 'Pages they can open',
  previewActions: 'Actions they can use',
  previewLastChange: 'Your last change',
  previewWaiting: 'Change a level or an action on the left to see what it does.',
  previewNowAllowed: 'now allowed',
  previewRemoved: 'removed',
  previewMenu: 'Their menu',
  previewPageList: 'Their pages',
  previewCanDoOn: 'What they can do on',
  previewAllowed: 'Allowed',
  previewNotAllowed: 'Not allowed',
  previewMore: 'more',
  previewLandingNone: 'No default landing page: they start on the normal home page.',
  previewLandingOk: (page: string) => `After signing in they start on ${page}.`,
  previewLandingBlocked: (page: string) => `They are set to start on ${page}, but cannot open it yet.`,
  actionHint: (name: string) =>
    ({
      access: 'Open and view the page',
      view: 'View the page',
      read: 'View the page',
      add: 'Create new items',
      create: 'Create new items',
      edit: 'Change existing items',
      update: 'Change existing items',
      delete: 'Delete items',
      export: 'Download lists',
      activity: 'See the activity log',
    })[name.toLowerCase()] ?? name,
  profileDetails: 'Profile',
  userDetails: 'User details',
  contactGroupDetails: 'Contact group details',
  accessProfileDetails: 'Access profile details',
  accessProfileDetailsHint: 'Name, external key and the page users land on',
  siteAccessHint: 'Tick what this profile may open and do',
  contactGroupDetailsHint: 'Name, description and where its mail is sent',
  contactGroupMembersHint: 'Who receives mail for this group',
  // User details studio split (D-018 frame, Settings card language); legacy has no keys for these.
  accountHint: 'Sign-in name, contact details and the linked student record',
  passwordHint: 'Set the first password for this account',
  accessCard: 'Access',
  accessHint: 'What this user can open and do',
  userPreview: 'User preview',
  userPreviewHint: 'Updates as you type',
  previewNoName: 'New user',
  previewInactive: 'Inactive',
  previewActive: 'Active',
  previewNoEmail: 'No email address',
  previewNoStudent: 'No student linked',
  previewPersonas: 'Access profiles',
  previewNoPersonas: 'No access profile chosen',
  previewSuperUser: 'Super user: every school, course and module',
  previewOwnClasses: 'Own classes only',
  previewNoScope: 'No security scope set',
  previewMobileOn: 'Mobile app logging on',
  previewMobileOff: 'Mobile app logging off',
  previewAfterSave: 'After saving you can set a password or send a reset link from here.',
  previewSetup: 'Setup',
  previewSetupOf: (done: number, total: number) => `${done} of ${total}`,
  previewStepUserName: 'Sign-in name',
  previewStepFullName: 'Full name',
  previewStepEmail: 'Email address',
  previewStepAccess: 'Access profile',
  previewStepPassword: 'Password',
  previewAccount: 'Account',
  previewSignsInWith: 'Signs in with',
  previewSignInSeats: 'SEAtS password',
  previewSignInCompany: 'Company sign-in',
  previewUserId: 'User ID',
  previewSuperUserBadge: 'Super user',
  ruleLength: 'At least ten characters',
  ruleUpper: 'An uppercase letter (A–Z)',
  ruleLower: 'A lowercase letter (a–z)',
  ruleDigit: 'A digit (0–9)',
  ruleSymbol: 'A symbol (!$#,%)',
  ruleNotUserName: 'Does not contain the user name',
  ruleMatch: 'Confirmation matches',
  passwordRulesLabel: 'Password requirements',
} as const

export type UsersTextKey = keyof typeof USERS_TEXT

export const isUsersTextKey = (key: string): key is UsersTextKey => Object.hasOwn(USERS_TEXT, key)

const KEYS = Object.keys(USERS_TEXT)

export function useUsersText() {
  const resources = useResources(KEYS)
  const { text } = resources
  const t = useCallback(
    (key: UsersTextKey) => {
      const value = text(key)
      return !value.trim() || value === key ? USERS_TEXT[key] : value
    },
    [text],
  )
  return t
}
