'use client'

import { useCallback } from 'react'
import { useResources } from '@/shared/resources'

// Keys requested by seats-admin-engagement.html:151-176 and the history component; fallbacks are readable English.
export const ENGAGEMENT_TEXT = {
  Engagement: 'Engagement',
  Configuration: 'Configuration',
  History: 'History',
  Add: 'Add',
  ReCalculate: 'Re-calculate',
  Name: 'Name',
  IsActive: 'Is Active',
  LastRun: 'Last Run',
  SelectedModel: 'Select at least one model.',
  AddNewModel: 'Add new model',
  DefaultSetup: 'Default setup',
  Option: 'Option',
  CopyExisting: 'Copy existing',
  Models: 'Models',
  ActiveModelsInSelection: 'Active models in selection',
  ReSyncStudents: 'Re-sync students',
  Run: 'Run',
  ReCalculateModels: 'Re-calculate models',
  Selected: 'Selected',
  Save: 'Save',
  Cancel: 'Cancel',
  Select: 'Select',
  NameIsRequired: 'The Name is required.',
  DateRange: 'Date Range',
  From: 'From',
  To: 'To',
  SelectRange: 'Select Range',
  Today: 'Today',
  Loading: 'Loading',
  Refresh: 'Refresh',
  Collapse: 'Collapse',
  Clear: 'Clear',
  Total: 'Total',
  SelectAll: 'Select all',
  AlertSaveErrorDefault: 'There was an error while trying to save the item.',
  AlertGeneralErrorDefault: 'There was an error while processing your request.',
  NumberOfItemsPerPage: 'Number of items per page',
  Of: 'of',
  Previous: 'Previous',
  Next: 'Next',
  View: 'View',
  Stats: 'Stats',
  StudentScore: 'Student Score',
  IsTrainingPeriod: 'Is Training Period',
  All: 'All',
  Yes: 'Yes',
  No: 'No',
  Nodes: 'Nodes',
  Students: 'Students',
  Status: 'Status',
  Containing: 'Containing',
  Search: 'Search',
  RefreshInterval: 'Refresh Interval',
  Never: 'Never',
  SortBy: 'Sort by',
  Period: 'Period',
  Calculated: 'Calculated',
  Training: 'Training',
  Model: 'Model',
  Node: 'Node',
  Instances: 'Instances',
  Min: 'Min',
  Max: 'Max',
  Mean: 'Mean',
  SD: 'SD',
  Errors: 'Errors',
  Warnings: 'Warnings',
  Messages: 'Messages',
  StudentId: 'Student Id',
  Export: 'Export',
  ExportToCSV: 'Export to CSV',
  ExportToPDF: 'Export to PDF',
  ReportProcessing: 'The report is being processed. You will be notified when it is ready.',
  Close: 'Close',
  Error: 'Error',
  Finished: 'Finished',
  Idle: 'Idle',
  Persisting: 'Persisting',
  Processing: 'Processing',
  Filters: 'Filters',
  ModelName: 'Model Name',
  ModelAppliedTo: 'Model applied to',
  Include: 'Include',
  Exclude: 'Exclude',
  Category: 'Category',
  Value: 'Value',
  StudentType: 'Type',
  StudentYear: 'Student Year',
  Faculty: 'College',
  School: 'School',
  Programme: 'Programme',
  Course: 'Course',
  Weight: 'Weight',
  Decay: 'Decay',
  Patience: 'Patience',
  Threshold: 'Threshold',
  MinZ: 'Min Z',
  MaxZ: 'Max Z',
  Url: 'Url',
  Key: 'Key',
  Back: 'Back',
  Delete: 'Delete',
  None: 'None',
  RequiredMessage: 'There are fields with input validation errors.',
  DatasetBuilding: 'Dataset Building',
  And: 'And',
  Because: 'Because',
  OfType: 'Of Type',
  Calculate: 'Calculate',
  ExportProfileSet: 'Export Profile Set',
  WithdrawlBetweenRange: 'Withdrawn between range',
  OrHadAssessmenteBetweenRange: 'Or had assessment between range',
  CollegeYear: 'College Year',
  TheNodeHasRunSuccessfully: 'The node has run successfully',
  EventsRange: 'Events Range',
  AlertSaveSucceededDefault: 'The item was saved successfully.',
} as const

export const ENGAGEMENT_FALLBACK_ONLY = {
  noAccess: 'You do not have permission to view this page.',
  noItems: 'There are no items to show.',
  expand: 'Expand',
  first: 'First',
  last: 'Last',
  active: 'Active',
  inactive: 'Inactive',
  never: 'Never',
  select: 'Select',
  dismiss: 'Dismiss',
  safeMode: 'Saving is turned off in this environment (safe mode).',
  created: 'The model was created.',
  recalculating: 'Re-calculation has started.',
  addHelp: 'Start from the default setup or copy an existing model.',
  recalcHelp: 'Choose which models to run and for which dates.',
  selectedHelp: 'Every ticked model',
  activeHelp: 'Skips inactive models',
  defaultHelp: 'A new model with the standard nodes',
  copyHelp: 'Starts as a copy of another model',
  chooseMonthYear: 'Choose month and year',
  buildingHelp: 'Who the model is trained on, and the counts behind it',
  buildingRules: 'Dataset building rules',
  runNode: 'Run',
  runNodeHelp: 'Runs this node over the events range above.',
  nodesHelpRange: 'Run uses this range, as the legacy events range does.',
  and: 'And',
  because: 'Because',
  ofType: 'Of type',
  calculate: 'Calculate',
  exportProfileSet: 'Export profile set',
  exportNeedsStudents: 'There are no students to export.',
  exportQueued: 'The export is being processed. You will be notified when it is ready.',
  countsFailed: 'The student counts could not be worked out.',
  studentsInRules: 'Students',
  studentsWithdrawn: 'Students',
  studentsAssessed: 'Students',
  withdrawnBetween: 'Withdrawn between range',
  assessmentBetween: 'Or had assessment between range',
  assessmentNeedsWithdrawal: 'Assessment dates are only used when a withdrawal range is set.',
  last7Days: 'Last 7 days',
  last14Days: 'Last 14 days',
  last30Days: 'Last 30 days',
  close: 'Close',
  reset: 'Clear filters',
  expandFilters: 'Show filters',
  collapseFilters: 'Hide filters',
  activeFilters: 'Applied filters',
  views: 'Views',
  seconds: 'seconds',
  modelsSelected: (count: number) => `${count} model/s selected`,
  nodesSelected: (count: number) => `${count} node/s selected`,
  statusSelected: (count: number) => `${count} status selected`,
  periodNewest: 'Period (Newest - Oldest)',
  periodOldest: 'Period (Oldest - Newest)',
  calculatedNewest: 'Calculated (Newest - Oldest)',
  calculatedOldest: 'Calculated (Oldest - Newest)',
  studentHint: 'All',
  clearStudent: 'Clear student',
  noMessages: 'There are no messages.',
  exportBlocked: 'Exporting is turned off in this environment (safe mode).',
  exporting: 'Exporting…',
  exportPrompt: 'Choose a file format for this history list.',
  exportPdfHint: 'Formatted for printing',
  exportCsvHint: 'Opens in Excel',
  model: 'Model',
  modelDetails: 'Model details',
  ruleIncludeRequired: 'Choose Include or Exclude.',
  ruleCategoryRequired: 'Choose a category.',
  ruleValueRequired: 'Choose a value.',
  copyNeedsModel: 'Choose a model to copy to enable Save.',
  modelHelp: 'Name and status of this engagement model.',
  appliedHelp: 'Students this model is calculated for.',
  nodesHelp: 'Tick a node to use it and set its weight and settings.',
  notFound: 'The model could not be found.',
  unsaved: 'Unsaved changes',
  viewOnly: 'View only',
  discard: 'Discard',
  leaveConfirm: 'You have unsaved changes. Leave this page?',
  equals: '=',
  noRules: 'There are no rules.',
  ruleExists: 'This rule is already in the list.',
  defaultPlaceholder: 'default',
  invalidUrl: 'Please enter a valid URL.',
  lookupFailed: 'An error occurred when trying to obtain the values for the selected category.',
  searchValue: 'Search',
  expandNode: 'Expand',
  collapseNode: 'Collapse',
  legacyOnly: 'The prevalence charts and Map To are only in the legacy editor for now.',
  openLegacy: 'Open legacy editor',
  decayNumber: (name: string) => `The decay for ${name} must be a number`,
  decayRange: (name: string) => `The decay for ${name} should be a value between 0.01 and 0.99`,
  notANumber: (name: string, field: string) => `The ${field} for ${name} must be a number`,
  rulesCount: (count: number) => `${count} rule/s`,
} as const

export type EngagementTextKey = keyof typeof ENGAGEMENT_TEXT

const KEYS = Object.keys(ENGAGEMENT_TEXT)

export function useEngagementText() {
  const { text } = useResources(KEYS)
  return useCallback(
    (key: EngagementTextKey) => {
      const value = text(key)
      return !value.trim() || value === key ? ENGAGEMENT_TEXT[key] : value
    },
    [text],
  )
}

export type EngagementText = ReturnType<typeof useEngagementText>
