// English-only wording for the Console rail and the Briefing preview; the legacy Admin has no resource keys for these.
export const BRIEFING_EN = {
  areas: 'Applications',
  closed: 'closed',
  granted: 'granted',
  pagesOpen: 'pages they can open',
  thingsAllowed: 'things they can do',
  pagesClosed: 'pages closed',
  canDoHere: 'Allowed',
  closedHere: 'Restricted',
  neverSee: 'Pages they will never see',
  remove: 'remove',
  allow: 'allow',
  openIt: 'open it',
  nothingAllowed: 'Nothing yet. Grant an action on the left.',
  nothingClosed: 'Nothing is closed on this page.',
  nothingShut: 'Nothing is fully closed. Every page is reachable.',
  customMix: 'Custom mix',
  updating: 'updating',
  tapHint: 'Every line here is a button. Tap to allow or remove.',
  onPage: 'On ',
  theyCan: ' they can ',
  andMore: (count: number) => ` and ${count} more`,
  butClosed: (count: number) => `, but ${count} ${count === 1 ? 'action is' : 'actions are'} closed`,
  nothingAtAll: 'do nothing at all',
  noneClosed: ', and nothing is closed',
  fullStop: '.',
  moreAllowed: (count: number) => `+${count} more allowed`,
  moreClosed: (count: number) => `+${count} more restricted`,
  morePages: (count: number) => `+${count} more closed pages`,
  allBlocked: (area: string, count: number) => `${area} · all ${count} actions blocked`,
  shownOf: (shown: number, total: number) => `${shown} of ${total} permissions shown`,
  updated: 'updated',
  grantedOf: (granted: number, total: number) => `${granted} of ${total} actions granted`,
  count: (granted: number, total: number) => `${granted}/${total}`,
} as const

// The three visibility lenses reuse the Briefing panel; only the nouns change.
export const VISIBILITY_EN = {
  visibleHere: 'Visible',
  hiddenHere: 'Hidden',
  nothingHidden: 'Nothing is hidden here.',
  moreVisible: (n: number) => `+${n} more visible`,
  moreHidden: (n: number) => `+${n} more hidden`,
  morePages: (n: number) => `+${n} more`,
  tapHint: 'Every line here is a button. Tap to show or hide.',
  events: {
    hint: 'What shows on a student timeline.',
    open: 'event types they see',
    allowed: 'come with details',
    shut: 'event types hidden',
    lead: 'On a timeline they see ',
    empty: 'No event type is visible yet. Turn one on to the left.',
    shutTitle: 'Hidden from every timeline',
    withComments: (n: number) => `, and comments on ${n}.`,
    noComments: '.',
  },
  cases: {
    hint: 'Which case types this profile may open.',
    open: 'case types they open',
    allowed: 'case types in total',
    shut: 'case types closed',
    lead: 'They can open ',
    empty: 'No case type is open yet. Turn one on to the left.',
    shutTitle: 'Cases they cannot open',
  },
  workflows: {
    hint: 'Which workflows this profile may act in.',
    open: 'workflows they act in',
    allowed: 'workflows in total',
    shut: 'workflows closed',
    lead: 'They can act in ',
    empty: 'No workflow is open yet. Turn one on to the left.',
    shutTitle: 'Workflows they cannot touch',
  },
} as const
