// English-only wording for the Console rail and the Briefing preview; the legacy Admin has no resource keys for these.
export const BRIEFING_EN = {
  areas: 'Applications',
  closed: 'closed',
  granted: 'granted',
  pagesOpen: 'pages they can open',
  thingsAllowed: 'things they can do',
  pagesClosed: 'pages closed',
  canDoHere: 'Allowed',
  closedHere: 'Restricted',
  neverSee: 'Pages they will never see',
  remove: 'remove',
  allow: 'allow',
  openIt: 'open it',
  nothingAllowed: 'Nothing yet. Grant an action on the left.',
  nothingClosed: 'Nothing is closed on this page.',
  nothingShut: 'Nothing is fully closed. Every page is reachable.',
  customMix: 'Custom mix',
  updating: 'updating',
  tapHint: 'Every line here is a button. Tap to allow or remove.',
  onPage: 'On ',
  theyCan: ' they can ',
  andMore: (count: number) => ` and ${count} more`,
  butClosed: (count: number) => `, but ${count} ${count === 1 ? 'action is' : 'actions are'} closed`,
  nothingAtAll: 'do nothing at all',
  noneClosed: ', and nothing is closed',
  fullStop: '.',
  moreAllowed: (count: number) => `+${count} more allowed`,
  moreClosed: (count: number) => `+${count} more restricted`,
  morePages: (count: number) => `+${count} more closed pages`,
  allBlocked: (area: string, count: number) => `${area} · all ${count} actions blocked`,
  shownOf: (shown: number, total: number) => `${shown} of ${total} permissions shown`,
  updated: 'updated',
  grantedOf: (granted: number, total: number) => `${granted} of ${total} actions granted`,
  count: (granted: number, total: number) => `${granted}/${total}`,
} as const
