import {
  BookOpen,
  Building,
  Calculator,
  CalendarClock,
  CalendarPlus,
  CircleCheck,
  CircleHelp,
  Cloud,
  Cpu,
  FileCode,
  Gauge,
  GitBranch,
  GitFork,
  GraduationCap,
  History,
  KeyRound,
  ListChecks,
  Lock,
  Mail,
  Plug,
  Recycle,
  Settings,
  Tags,
  Undo2,
  Upload,
  User,
  Users,
  type LucideIcon,
} from 'lucide-react'
import type { MenuIcon } from './admin-menu'

export const MENU_ICONS: Record<MenuIcon, LucideIcon> = {
  users: Users,
  user: User,
  lock: Lock,
  history: History,
  key: KeyRound,
  cpu: Cpu,
  building: Building,
  calculator: Calculator,
  help: CircleHelp,
  settings: Settings,
  fileCode: FileCode,
  calendarPlus: CalendarPlus,
  tags: Tags,
  listChecks: ListChecks,
  mail: Mail,
  cloud: Cloud,
  undo: Undo2,
  calendarClock: CalendarClock,
  fork: GitFork,
  branch: GitBranch,
  book: BookOpen,
  upload: Upload,
  gauge: Gauge,
  check: CircleCheck,
  graduation: GraduationCap,
  recycle: Recycle,
  plug: Plug,
}
